@baseUrl = http://localhost:5001

@urlPath = api/v1

###
POST {{baseUrl}}/{{urlPath}}/signup
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "username": "lulu3434",
  "email": "lulu@gmail.com",
  "password": "123456"
}

###
POST {{baseUrl}}/{{urlPath}}/signin
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "username": "mau8795",
  "password": "123456"
}

###
GET {{baseUrl}}/{{urlPath}}/signout
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/main
Content-Type: application/json
Accept: application/json
withCredentials: true

###
POST {{baseUrl}}/{{urlPath}}/createVideo
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "title": "Best Progressive House",
  "description": "The best music for coding",
  "link": "https://www.youtube.com/watch?v=DzfyleInDKg",
  "category": "House techno"
}

###
GET {{baseUrl}}/{{urlPath}}/searchVideo/64769460fe2ef6ffc8968fe1
Content-Type: application/json
Accept: application/json
withCredentials: true

###
POST {{baseUrl}}/{{urlPath}}/video/6478e9a1c92c38f282c18f97/createComment
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "text": "Too much, esa vaina es muy extraña"
}

###
PUT {{baseUrl}}/{{urlPath}}/editComment/647a2df49677aabbdca47406
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "text": ""
}

###
DELETE {{baseUrl}}/{{urlPath}}/deleteComment/647a950edfd12b3a7e5ff1da
Content-Type: application/json
Accept: application/json
withCredentials: true
