@baseUrl = http://localhost:5001

@urlPath = api/v1

###
POST {{baseUrl}}/{{urlPath}}/signup
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "username": "leo0406",
  "email": "leo@gmail.com",
  "password": "123456"
}

###
POST {{baseUrl}}/{{urlPath}}/signin
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "username": "mau8795",
  "password": "123456"
}

###
GET {{baseUrl}}/{{urlPath}}/signout
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/main
Content-Type: application/json
Accept: application/json
withCredentials: true

###
POST {{baseUrl}}/{{urlPath}}/createVideo
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "title": "Best Progressive House",
  "description": "The best music for coding",
  "link": "https://www.youtube.com/watch?v=DzfyleInDKg",
  "category": "House techno"
}

###
GET {{baseUrl}}/{{urlPath}}/searchVideo/647a0c4683330a54146688b0
Content-Type: application/json
Accept: application/json
withCredentials: true

###
POST {{baseUrl}}/{{urlPath}}/video/647a0c9d83330a54146688b6/createComment
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "text": "Bueeenaaa!"
}
